### ISSUE TITLE
BottomNavigationView activeIndicator color is always grey in color

### ISSUE THREAD

**Issue by rev0lgenX** [pranavpandey/dynamic-support#19]
**Description:** DynamicBottomNavigationView active indicator container color is always grey is color

**Expected behavior:** Looking at the code isn't it suppose to be translucent accent in color? But it seems it always show translucent grey.

![Screenshot_20230108-094831_Dynamic Support](https://user-images.githubusercontent.com/20517801/211180208-a3278088-0c01-4841-a04f-733f686ed77c.jpg)

**Sample app and/or repro:** Official Sample App

**Android API version:** Android API version. `API 29`

**Library version:** The Library version you are using. `6.2.0`

**Device:** Device on which the bug was encountered. `Samsung Galaxy Note 9`

**Comment by pranavpandey** [comment]
Yes, but it was not allowing any other color except the alpha component. So, the idea was to at least match the alpha to avoid any visibility issues.

I think it's by choice and related to [MDC-Android](https://github.com/material-components/material-components-android) based on [Material Design 3](https://m3.material.io/components/navigation-bar/overview).

**Comment by rev0lgenX** [comment]
I mean isn't it supposed to be translucent accent color like the screenshot below. But right now I think it is always in translucent grey in color

![Screenshot_20230109-084325_AniLib](https://user-images.githubusercontent.com/20517801/211234591-c7345653-999f-4948-84cd-d5e884877036.jpg)

**Comment by pranavpandey** [comment]
No, according to [M3 guidelines](https://m3.material.io/components/navigation-bar/guidelines), it picks the color from the background. You can set any color for the icon, but the active indicator color should be based on the bottom navigation background color i.e; a darker variant of white color (Gray) in your case.

`DynamicBottomNavigationView` just extends the `BottomNavigationView` provided by MDC-Android and tries to apply the calculated colors at runtime. For now, it just applies (and doesn't allow to change) a `translucent gray` color by default to provide an effect as suggested by the new guidelines.

**Comment by rev0lgenX** [comment]
I am really confused. After setting background color for `DynamicBottomNavigationView `, I think its still showing grey. Is it supposed to be this way? 



![Screenshot_20230109-095130_Dynamic Support](https://user-images.githubusercontent.com/20517801/211240025-4e221a1f-be99-4f48-8560-fd7c5964ee94.jpg)
![Screenshot_20230109-094322_Dynamic Support](https://user-images.githubusercontent.com/20517801/211240031-2c3fe7da-4ca8-43b3-8644-f5a11ee54c64.jpg)
![Screenshot_20230109-095233_Dynamic Support](https://user-images.githubusercontent.com/20517801/211240033-ea48cc73-212d-486e-a9f6-615c63446094.jpg)

**Comment by pranavpandey** [comment]
Yes, this is the closest effect you can get based on the latest guidelines.

The thing I am trying to explain is that they have fixed the `gray` color internally due to which the `code` you have pointed out is unable to change its color. So, this issue is kind of related to [MDC-Android](https://github.com/material-components/material-components-android).

**Comment by rev0lgenX** [comment]
Okay, thank you for the explanation.
