### ISSUE TITLE
dialog corner radius not found 

### ISSUE THREAD

**Issue by dhvanit-vavdiya** [pranavpandey/dynamic-support#2]
library version:
// For AndroidX enabled projects.
    implementation 'com.pranavpandey.android:dynamic-support:2.1.0'

    // For legacy projects.
    implementation 'com.pranavpandey.android:dynamic-support:1.3.0'

gradle version:
        classpath 'com.android.tools.build:gradle:3.2.1'

Android resource linking failed
Output:  D:\dhvnit\cfll\cfll\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
D:\dhvnit\cfll\cfll\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
D:\dhvnit\cfll\cfll\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1852: error: resource android:attr/fontVariationSettings not found.
D:\dhvnit\cfll\cfll\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1852: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: C:\Users\Lenovo\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\ad8871029d632d9c6e9834f526f8b891\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
        C:\Users\Lenovo\AppData\Local\Android\Sdk\platforms\android-27\android.jar\
        --manifest\
        D:\dhvnit\cfll\cfll\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
        -o\
        D:\dhvnit\cfll\cfll\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
        -R\
        @D:\dhvnit\cfll\cfll\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        D:\dhvnit\cfll\cfll\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
        --proguard-main-dex\
        D:\dhvnit\cfll\cfll\app\build\intermediates\legacy_multidex_aapt_derived_proguard_rules\debug\processDebugResources\manifest_keep.txt\
        --custom-package\
        com.cricketfastlive\
        -0\
        apk\
        --no-version-vectors\
        --output-text-symbols\
        D:\dhvnit\cfll\cfll\app\build\intermediates\symbols\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

**Comment by pranavpandey** [comment]
This issue generally occurs when we have different compile versions for library and project.

From your log, I can see that you are using SDK 27 for compiling the project. This library uses SDK 28 so, please try to add the below line in your app level `build.gradle` file:

```groovy
android {
    compileSdkVersion 28
    ...
}
```

For more info, please check the [sample](https://github.com/pranavpandey/dynamic-support/blob/master/sample/build.gradle).

**Comment by MehdiRaza1998** [comment]
I had this problem, i tried a lot of things to solve it. But when I revert my local changes (youu can do it by right clicking app option then show local history then you can revert the changes) , and noticed that it was gone, but when I added implementation of any google related api again the error returned.

So solution is , you have to keep the api version of google or any similar api providers the same. my google map and location were of 16.0.4 i guess while other api of google was of 17.0.0 which caused this error, probably because it was using androidX. So I changed it to 16.0.0 and BOOM! Problem solved! :)

**Comment by pranavpandey** [comment]
Thanks!
