### ISSUE TITLE
Don't working setOnApplyWindowInsetsListener

### ISSUE THREAD

**Issue by deadfan** [pranavpandey/dynamic-support#21]
**Description:** I had a problem after updating components 6.0.0 then to 6.3.0 (And also a new sdk). I used the usual methods, but they all failed (addFlags. I didn’t find any guides on how to fix this, but if you help me, I’ll be glad. I also can’t use ViewCompat.setOnApplyWindowInsetsListener, although I was able to figure it out and do what My botton was fine, but I need where the ToolBarLayout was to have a marginTop according to the size of the statusBar

**Expected behavior:** 
![image](https://github.com/pranavpandey/dynamic-support/assets/53148768/7186a959-9fe7-45b1-bdf9-4f113d325a0b)

**Source code:** 
class AppBarLayout : DynamicAppBarLayout 
`override fun applyWindowInsets() {
        ViewCompat.setOnApplyWindowInsetsListener(
            this
        ) { v, insets ->
            v.setPadding(
                paddingLeft+ insets.getInsets(WindowInsetsCompat.Type.systemBars()).left,
                paddingTop,
                paddingRight+ insets.getInsets(WindowInsetsCompat.Type.systemBars()).right,
                v.paddingBottom
            )
            insets
        }
}`
class Toolbar: DynamicAppBarLayout 
`override fun applyWindowInsets() {
        ViewCompat.setOnApplyWindowInsetsListener(this) { v, insets ->
            (v.layoutParams as MarginLayoutParams).also {
                it.setMargins(
                    0,
                    insets.getInsets(WindowInsetsCompat.Type.systemBars()).top,
                    0,
                    0
                )
            }
            insets
        }
    }`

**Sample app and/or repro:** [OPTIONAL] A sample app or steps to reproduce the issue. You may attach a `zip` or `APK` file of the sample app or a link to the GitHub repository.

**Android API version:** Android API version. `API 29`

**Library version:** The Library version you are using. `6.3.0`

**Device:** Device on which the bug was encountered. `Honor 10i (Model: HRY-LX1T)`

**Comment by pranavpandey** [comment]
Thanks for the details!

You can try to use the [DynamicViewUtils](https://github.com/pranavpandey/dynamic-utils/blob/master/dynamic-utils/src/main/java/com/pranavpandey/android/dynamic/util/DynamicViewUtils.java) to apply insets (`applyWindowInsetsVertical(view, consume)`) accordingly.

**Comment by deadfan** [comment]
Thank you, now I have everything in order.  But I would like to make the statusbar transparent in certain fragments, otherwise it doesn’t work out nicely.![Screenshot_20230920_201156_ru.aniusoft.aniu.debug.jpg](https://github.com/pranavpandey/dynamic-support/assets/53148768/c48db5e1-ebe0-4765-94c7-37ef6bb97d26)
