### ISSUE TITLE
Short description of the issue

### ISSUE THREAD

**Issue by deadfan** [pranavpandey/dynamic-support#22]
**Description:** The text is not centered. I used `android:gravity="center"` and even included `app:adt_rtlSupport="true"` I tried all this through the code, I tried adding `textAlignment = TEXT_ALIGNMENT_CENTER`, but nothing works (the text still remains at start)

**Android API version:** Android API version. `API 29`

**Library version:** The Library version you are using. `6.3.0`

**Device:** Device on which the bug was encountered. `Honor 10i (Model: HRY-LX1T)`

**Comment by pranavpandey** [comment]
It provides RTL support by default by setting the gravity to `start`. However, you can restrict this behavior by adding app:adt_rtlSupport="false" to the specific views.

**Comment by deadfan** [comment]
![image](https://github.com/pranavpandey/dynamic-support/assets/53148768/c17e00bb-50e3-405d-98ad-00695517cbc8)
