### ISSUE TITLE
Demo: Smooth transition on changing color

### ISSUE THREAD

**Issue by subpub** [pranavpandey/dynamic-support#8]
Currently, on changing colors there is a black screen for a small moment (on demo app). It should be possible to get a smooth transition

**Comment by pranavpandey** [comment]
This is a known issue and I think it is related to the Android API and `recreate()` method of the activity. For now, you can use your own implementation to resolve it:

```java
@Override
protected void onAppThemeChange() {
    Intent intent = getIntent();
    finish();
    startActivity(intent);
    overridePendingTransition(0, 0);
}
```

_This solution will not save the activity state and it will launch it from the start._

**Comment by subpub** [comment]
Thanks!

**Comment by pranavpandey** [comment]
I have tested a partial solution for slightly smoother animation. The key here is to use a custom window animation while recreating the activity. It will use a custom fade-in-out animation by default in the next release but it can be implemented right now by using the below code.

```java
@Override
protected void onAppThemeChange() {
    getWindow().setWindowAnimations(R.style.AnimationFadeInOut);
    ActivityCompat.recreate(this);
}
```
